function com_evolonix_RubiksCube(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',gb='&',r='/',ac='0442E745BA74B065601357108A9FD6CB.cache.html',Eb='332854E3BEBABB4B113BA9D07937494F.cache.html',bc='55C0CB077E1E0D5573E00F5AB1FE5AD5.cache.html',xb='5D9A325F5D9A1E1766F0D8EE2B6F6DD7.cache.html',Fb='6A49DDB453A525BA06B47C8E563E223E.cache.html',cc='84EE2EFFFFCF549D11CC859D303201E5.cache.html',Db='8727FCF90286952307293A1BC42A8C58.cache.html',fc='<script defer="defer">com_evolonix_RubiksCube.onInjectionDone(\'com.evolonix.RubiksCube\')<\/script>',ic='<script id="',A='=',q='?',Bb='B4D6E53DC58C758B96DA5EAB529E3194.cache.html',C='Bad handler "',Cb='C02AD7ECA9DB8E80818862160F374FA8.cache.html',Ab='D8B6C227E7C245E0B3FA4E5214909832.cache.html',ec='DOMContentLoaded',o='SCRIPT',jb='Unexpected exception in locale detection, using default: ',ib='_',hc='__gwt_marker_com.evolonix.RubiksCube',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',m='com.evolonix.RubiksCube',z='content',hb='default',zb='en',gc='end',rb='gecko',sb='gecko1_8',yb='gwt.hybrid',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',wb='hosted.html?com_evolonix_RubiksCube',qb='ie6',ab='iframe',t='img',bb="javascript:''",ub='loadExternalRefs',fb='locale',v='meta',eb='moduleRequested',dc='moduleStartup',pb='msie',w='name',lb='opera',db='position:absolute;width:0;height:0;border:none',ob='safari',vb='selectingPermutation',x='startup',tb='unknown',kb='user.agent',mb='webkit';var kc=window,k=document,jc=kc.__gwtStatsEvent?function(a){return kc.__gwtStatsEvent(a)}:null,Ec,uc,pc,oc=l,xc={},bd=[],Dc=[],nc=[],Ac,Cc;jc&&jc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!kc.__gwt_stylesLoaded){kc.__gwt_stylesLoaded={}}if(!kc.__gwt_scriptsLoaded){kc.__gwt_scriptsLoaded={}}function tc(){try{return kc.external&&(kc.external.gwtOnLoad&&kc.location.search.indexOf(yb)==-1)}catch(a){return false}}
function wc(){if(Ec&&uc){var c=k.getElementById(m);var b=c.contentWindow;b.__gwt_initHandlers=com_evolonix_RubiksCube.__gwt_initHandlers;if(tc()){b.__gwt_getProperty=function(a){return qc(a)}}com_evolonix_RubiksCube=null;b.gwtOnLoad(Ac,m,oc);jc&&jc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:gc})}}
function rc(){var j,h=hc,i;k.write(ic+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){oc=f(j.src)}if(oc==l){var e=k.getElementsByTagName(s);if(e.length>0){oc=e[e.length-1].href}else{oc=f(k.location.href)}}else if(oc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=oc+u;oc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function Bc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}xc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{Cc=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{Ac=eval(b)}catch(a){alert(C+b+F)}}}}}}
function mc(a,b){return b in bd[a]}
function lc(a){var b=xc[a];return b==null?null:b}
function ad(d,e){var a=nc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function qc(d){var e=Dc[d](),b=bd[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(Cc){Cc(d,a,e)}throw null}
var sc;function vc(){if(!sc){sc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);jc&&jc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(oc+Fc)}}
Dc[fb]=function(){try{var g;if(g==null){var b=location.search;var h=b.indexOf(fb);if(h>=0){var e=b.substring(h);var c=e.indexOf(A)+1;var d=e.indexOf(gb);if(d==-1){d=e.length}g=e.substring(c,d)}}if(g==null){g=lc(fb)}if(g==null){return hb}while(!mc(fb,g)){var f=g.lastIndexOf(ib);if(f==-1){g=hb;break}else{g=g.substring(0,f)}}return g}catch(a){alert(jb+a);return hb}};bd[fb]={'default':0,en:1};Dc[kb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(lb)!=-1){return lb}else if(d.indexOf(mb)!=-1){return ob}else if(d.indexOf(pb)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return qb}}}else if(d.indexOf(rb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return sb}return rb}return tb};bd[kb]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};com_evolonix_RubiksCube.onScriptLoad=function(){if(sc){uc=true;wc()}};com_evolonix_RubiksCube.onInjectionDone=function(){Ec=true;jc&&jc({moduleName:m,subSystem:x,evtGroup:ub,millis:(new Date()).getTime(),type:gc});wc()};rc();Bc();jc&&jc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:vb});var Fc;if(tc()){Fc=wb}else{try{ad([hb,rb],xb);ad([zb,rb],Ab);ad([hb,lb],Bb);ad([zb,lb],Cb);ad([hb,ob],Db);ad([zb,ob],Eb);ad([hb,qb],Fb);ad([zb,qb],ac);ad([hb,sb],bc);ad([zb,sb],cc);Fc=nc[qc(fb)][qc(kb)]}catch(a){return}}var zc;function yc(){if(!pc){pc=true;wc();if(k.removeEventListener){k.removeEventListener(ec,yc,false)}if(zc){clearInterval(zc)}}}
if(k.addEventListener){k.addEventListener(ec,function(){vc();yc()},false)}var zc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){vc();yc()}},50);jc&&jc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:gc});jc&&jc({moduleName:m,subSystem:x,evtGroup:ub,millis:(new Date()).getTime(),type:nb});k.write(fc)}
com_evolonix_RubiksCube.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i()}finally{g&&g(a)}};d.onbeforeunload=function(a){var c,b;try{c=e()}finally{b=f&&f(a)}if(c!=null){return c}if(b!=null){return b}};d.onunload=function(a){try{j()}finally{h&&h(a);d.onresize=null;d.onbeforeunload=null;d.onunload=null}}};com_evolonix_RubiksCube();